# Generated by Django 4.2.5 on 2023-12-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_myuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
