# Generated by Django 4.2.5 on 2023-12-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
