version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /django/src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django/src
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
