# Generated by Django 4.2.5 on 2024-01-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger_chat', '0002_alter_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='users', to='messanger_chat.room'),
        ),
    ]
